language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ncbi-blast+
install:
  - pip install coveralls pytest-cov==2.6 pytest==3.2.3
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov geneblocks --cov-report term-missing

after_success:
  - coveralls
